routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GodController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\ThreadController;
use App\Http\Controllers\CommentController;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider and all of them will
  | be assigned to the "web" middleware group. Make something great!
  |
*/

// root
Route::get('/', function () {
    return view('welcome');
});

// God page for anyone
Route::get('/show/god/{god}', [GodController::class, 'show'])
	->name('show.god');
// Image for anyone
Route::get('/show/img/{image}', [ImageController::class, 'show'])
	->name('show.img');
// FAQ for anyone
Route::get('/faq', function() {
	return view('faq');
})->name('faq');
// Category page for anyone
Route::get('/show/category/{category}', [CategoryController::class, 'show'])
	->name('show.category');

Route::get('/show/threads/{god}', [ThreadController::class, 'index'])
	->name('show.threads');
Route::get('/show/thread/{thread}', [ThreadController::class, 'show'])
	->name('show.thread');

// logged in, but not email-verified
Route::middleware('auth')->group(function () {
	// profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// logged in, and email-verified
Route::middleware(['auth', 'verified'])->group(function () {
	// Admin manager
    Route::get('/manage/god/{god}', [GodController::class, 'manage'])
		->name('manage.god');
	Route::get('/manage/images', [ImageController::class, 'manage'])
		->name('manage.images');
    Route::get('/manage/categories', function () {
        return view('manage.categories');
    })->name('manage.categories');

	// dashboard for all users
	Route::get('/dashboard', function () {
		return view('dashboard');
	})->name('dashboard');
});

// api - some return JSON, some redirect (for form submit)
Route::middleware(['auth', 'verified'])->group(function () {
    // categories
    Route::get('/categories', [CategoryController::class, 'all']);
    Route::post('/category', [CategoryController::class, 'post']);
    Route::delete('/category/{category}', [CategoryController::class, 'delete']);
    Route::patch('/category/{category}', [CategoryController::class, 'patch']);

    // gods
    Route::get('/gods', [GodController::class, 'all']);
    Route::post('/god', [GodController::class, 'post']);
    Route::delete('/god/{god}', [GodController::class, 'delete']);
    Route::patch('/god/{god}', [GodController::class, 'patch']);

	// images
    Route::get('/imgs', [ImageController::class, 'json_paginate']);
    Route::post('/img', [ImageController::class, 'post']);
    Route::delete('/img/{image}', [ImageController::class, 'delete']);
    Route::patch('/img/{image}', [ImageController::class, 'patch']);
	// profile pictures
    Route::get('/pfp/{user}', [ProfileController::class, 'get_profile_picture']);
    Route::patch('/pfp', [ProfileController::class, 'set_profile_picture']);

	// Threads
    Route::post('/thread', [ThreadController::class, 'post']);
    Route::delete('/thread/{thread}', [ThreadController::class, 'delete']);
    Route::patch('/thread/{thread}', [ThreadController::class, 'patch']);
    Route::post('/comment', [CommentController::class, 'post']);
    Route::delete('/comment/{comment}', [CommentController::class, 'delete']);
    Route::patch('/comment/{comment}', [CommentController::class, 'patch']);
});

require __DIR__.'/auth.php';

app/View/Components/MasterLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class MasterLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.master');
    }
}

resources/views/layouts/app.blade.php
<x-master-layout>
	<div class="min-h-screen pb-10">
		@include('layouts.navigation')
		<div>
			<!-- Page Heading -->
			@if (isset($header))
			<header>
				<div class="flex justify-center max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 my-6">
					<h2 class="font-semibold text-xl text-yellow-200 leading-tight">
						{{ $header }}
					</h2>
				</div>
			</header>
			@endif

			<!-- God category hierearchy -->
			@if (isset($parents))
			@endif
		</div>

		<!-- Page Content -->
		<main class='max-w-7xl mx-auto h-max'>
			{{ $slot }}
		</main>
	</div>
</x-master-layout>

resources/views/layouts/guest.blade.php
<x-master-layout>
	<div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-900">
		<div>
			<a href="/">
				<x-application-logo class="w-20 h-20 fill-current text-gray-500" />
			</a>
		</div>

		<div class="w-full sm:max-w-md mt-6 px-6 py-4 shadow-md overflow-hidden sm:rounded-lg">
			{{ $slot }}
		</div>
	</div>
</x-master-layout>

resources/views/layouts/master.blade.php
<!DOCTYPE html>

<!-- make dark mode enabled by default -->
<html class='dark' lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ config('app.name', 'Laravel') }}</title>

	<!-- bladewind ui library -->
	<link href="{{ asset('vendor/bladewind/css/animate.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('vendor/bladewind/css/bladewind-ui.min.css') }}" rel="stylesheet" />
	<script src="{{ asset('vendor/bladewind/js/helpers.js') }}"></script>

	<!-- Fonts -->
	<link rel="preconnect" href="https://fonts.bunny.net">
	<link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

	<!-- theme settings -->
	<x-head.disable-dark-reader />

	<!-- Scripts -->
	@vite([
	'resources/css/app.css',
	'resources/js/app.js',
	])

</head>

<body class="font-sans antialiased bg-gray-900 text-gray-100">
	{{ $slot }}
</body>

</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }">
	<!-- Primary Navigation Menu -->
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="flex justify-between h-16">
			<div class="flex">
				<!-- Logo -->
				<div class="shrink-0 flex items-center">
					<a class='p-2 rounded-xl hover:bg-yellow-400/25 transition' href="{{ route('dashboard') }}">
						<x-application-logo class="block h-9 w-auto fill-current text-yellow-400" />
					</a>
				</div>

				<!-- Navigation Links -->
				<div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
					<x-nav-link class='text-yellow-200' :href="route('dashboard')" :active="request()->routeIs('dashboard')">
						Tableau de Bord
					</x-nav-link>

					@if (auth()->user()?->role['name'] == 'administrator')
					<x-nav-link class='text-yellow-200' :href="route('show.category', 1)" :active="request()->routeIs('show.category')">
						Catégories
					</x-nav-link>
					<x-nav-link class='text-yellow-200' :href="route('manage.images')" :active="request()->routeIs('manage.images')">
						Images
					</x-nav-link>
					@endif

				</div>
			</div>

			<!-- Settings Dropdown -->
			<div class="hidden sm:flex sm:items-center sm:ml-6">
				<x-dropdown align="right" width="48">
					<x-slot name="trigger">
						<button class="inline-flex items-center px-3 py-2 border border-transparent leading-4 font-medium rounded-md text-yellow-400 focus:outline-none transition ease-in-out duration-150">
							@if (auth()->check())
							<div>{{ Auth::user()->name }}</div>
							@endif

							<div class="ml-1">
								<svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
									<path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
								</svg>
							</div>
						</button>
					</x-slot>

					<x-slot name="content">
						<x-dropdown-div :href="route('profile.edit')">
							Profil
						</x-dropdown-div>

						<!-- Authentication -->
						<form method="POST" action="{{ route('logout') }}">
							@csrf

							<x-dropdown-div :href="route('logout')" onclick="event.preventDefault();
                                                this.closest('form').submit();">
								Déconnexion
							</x-dropdown-div>
						</form>
					</x-slot>
				</x-dropdown>
			</div>

			<!-- Hamburger -->
			<div class="-mr-2 flex items-center sm:hidden">
				<button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
					<svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
						<path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
						<path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
		</div>
	</div>

	<!-- Responsive Navigation Menu -->
	<div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
		<div class="pt-2 pb-3 space-y-1">
			<x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
				{{ __('Dashboard') }}
			</x-responsive-nav-link>
		</div>

		<!-- Responsive Settings Options -->
		<div class="pt-4 pb-1 border-t border-gray-200">
			@if (auth()->check())
			<div class="px-4">
				<div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
				<div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
			</div>
			@endif

			<div class="mt-3 space-y-1">
				<x-responsive-nav-link :href="route('profile.edit')">
					{{ __('Profile') }}
				</x-responsive-nav-link>

				<!-- Authentication -->
				<form method="POST" action="{{ route('logout') }}">
					@csrf

					<x-responsive-nav-link :href="route('logout')" onclick="event.preventDefault();
                                        this.closest('form').submit();">
						{{ __('Log Out') }}
					</x-responsive-nav-link>
				</form>
			</div>
		</div>
	</div>
</nav>